### ISSUE TITLE
安装完项目后，启动报错

### ISSUE THREAD

**Issue by wawow** [opensumi/app-desktop#6]
使用yarn安装完项目后启动报错
错误信息：
Unable to find Electron app at XXX
cannot find modele xxx/app-desktop/app/bootstrap/main.js
please verify that the package.json has a valid "main" entry
希望能给出解决办法

**Comment by erha19** [comment]
@wawow 请检查一下是否正确安装好依赖，同时请提供完整运行截图，无法判断是什么问题，我这边没有复现问题，运行下面命令启动
```
yarn && yarn build && yarn start
```

**Comment by wawow** [comment]
感谢，已经可以运行起来了
咱们这个opensumi如果想集成资源管理器和文件编辑部分到electron项目中，有什么文档或者教程吗？

**Comment by yantze** [comment]
运行起来后，打开一个文件夹就能查看文件和文件编辑了

**Comment by erha19** [comment]
@wawow 目前 OpenSumi 是不支持将单独的模块集成进 Electron 项目中的，我们推荐的方式还是基于 OpenSumi 底座，对原有的 Electorn 项目进行改造迁移。
